---
- hosts: webservers
  vars:
    domain: localhost
    apache_http_port: 81
    nginx_http_port: 80
    max_clients: 200
    virtualenv_dir: /srv/django/{{ domain }}

  remote_user: ubuntu
  sudo: yes
  tasks:


  - name: ensure apache is at the latest version
    apt: pkg=apache2 state=latest
  - name: install libapache2-mod-wsgi
    apt: pkg=libapache2-mod-wsgi state=latest
  - name: ensure python-dev is latest version
    apt: name=python3-dev update_cache=yes state=latest
  - name: ensure git is latest version
    apt: name=git update_cache=yes state=latest

  - name: create user deploy
    user: name=deploy group=www-data shell=/bin/bash 

  - name: create project directory
    file: path={{ virtualenv_dir }} owner=deploy group=www-data state=directory

  - name: create virtualenv
    shell: virtualenv {{ virtualenv_dir }}
    sudo_user: deploy

  - name: git checkout
    git: repo=https://github.com/mattxbart/crop.git
         dest={{ virtualenv_dir }}/crop

  - name: install web application dependencies
    pip: requirements={{ virtualenv_dir }}/crop/requirements.txt
         virtualenv={{virtualenv_dir}}

  - name: apache2 listen on port 81
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen {{ apache_http_port }}" state=present
  - name: write the apache config file
    template: src=roles/webtier/templates/apache.j2 dest=/etc/apache2/sites-enabled/{{ domain }}.conf
  - name: write the apache servername
    template: src=roles/webtier/templates/apache_servername.j2 dest=/etc/apache2/conf-enabled/servername.conf
    notify:
    - restart apache2

  - name: ensure nginx is at the latest version
    apt: pkg=nginx state=latest
  - name: remove default nginx conf
    file: path=/etc/nginx/sites-enabled/default state=absent 
  - name: write nginx config file
    template: src=roles/webtier/templates/nginx.j2 dest=/etc/nginx/sites-enabled/{{ domain }}.conf
    notify:
    - restart nginx
  - name: ensure nginx is running (and enable it at boot)
    service: name=nginx state=started enabled=yes

  

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart nginx
      service: name=nginx state=restarted